### ======================= Tag 模块 ===============================
### 获取所有标签接口测试
Get http://localhost:8000/api/v1/tags HTTP/1.1

### 新增标签
POST http://localhost:8000/api/v1/tags HTTP/1.1
content-type: application/json

{ "name": "css", "state": 0, "created_by": "MMQQ1" }

### 编辑标签
PUT http://localhost:8000/api/v1/tags/8 HTTP/1.1
content-type: application/json

{ "name": "CSS", "state": 0, "modified_by": "LIUZHEN_K" }

### 删除标签
DELETE http://localhost:8000/api/v1/tags/7 HTTP/1.1
content-type: application/json

{}

### ======================= Articles 模块 ===============================
### 获取所有文章列表
GET http://localhost:8000/api/v1/articles HTTP/1.1

### 获取某篇文章
GET http://localhost:8000/api/v1/articles/2 HTTP/1.1

### 添加文章
POST http://localhost:8000/api/v1/articles HTTP/1.1
content-type: application/json

{ 
  "tag_id": 5,
  "title": "Golang的一篇文章",
  "desc": "Golang的一篇文章",
  "content": "Golang是一门新的编程语言，是由Google维护的，开源的！",
  "created_by": "Kaindy Liu",
  "state": 0
}

### 修改文章
PUT http://localhost:8000/api/v1/articles/5 HTTP/1.1
content-type: application/json

{
  "tag_id": 6,
  "title": "Linux命令大集合",
  "desc": "Linux命令大集合",
  "content": "Linux命令大集合,Linux命令大集合,Linux命令大集合",
  "modified_by": "Liuzhen",
  "state": 0
}

### 删除文章
DELETE http://localhost:8000/api/v1/articles/2 HTTP/1.1
content-type: application/json

{}

### 测试获取Token
POST http://localhost:8000/auth HTTP/1.1
content-type: application/json

{ "username": "test", "password": "test123456" }