### 获取所有标签接口测试
Get http://localhost:8000/api/v1/tags HTTP/1.1

### 新增标签
POST http://localhost:8000/api/v1/tags HTTP/1.1
content-type: application/json

{ "name": "golang", "state": 0, "created_by": "Kaindy" }

### 编辑标签
PUT http://localhost:8000/api/v1/tags/5 HTTP/1.1
content-type: application/json

{ "name": "Golang", "state": 0, "modified_by": "LiuZhen" }