### ======================= Tag 模块 ===============================
### 获取所有标签接口测试
Get http://localhost:8000/api/v1/tags HTTP/1.1

### 新增标签
POST http://localhost:8000/api/v1/tags HTTP/1.1
content-type: application/json

{ "name": "css", "state": 0, "created_by": "MMQQ1" }

### 编辑标签
PUT http://localhost:8000/api/v1/tags/8 HTTP/1.1
content-type: application/json

{ "name": "CSS", "state": 0, "modified_by": "LIUZHEN_K" }

### 删除标签
DELETE http://localhost:8000/api/v1/tags/7 HTTP/1.1
content-type: application/json

{}

### ======================= Articles 模块 ===============================
### 获取所有文章列表
GET http://localhost:8000/api/v1/articles HTTP/1.1

### 获取某篇文章
GET http://localhost:8000/api/v1/articles/1 HTTP/1.1